config/routes.rb
Rails.application.routes.draw do
  resources :user_posts
  devise_for :admins
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "user_posts#index"
end

app/models/user_post.rb
class UserPost < ApplicationRecord
  def user
    User.find_by(id: self.user_id)
  end
end

app/controllers/user_posts_controller.rb
class UserPostsController < ApplicationController
  before_action :authenticate_user!, only: %i[ show edit update destroy ]
  before_action :set_user_post, only: %i[ show edit update destroy ]

  # GET /user_posts or /user_posts.json
  def index
    @user_posts = UserPost.all
  end

  # GET /user_posts/1 or /user_posts/1.json
  def show
  end

  # GET /user_posts/new
  def new
    @user_post = UserPost.new
  end

  # GET /user_posts/1/edit
  def edit
  end

  # POST /user_posts or /user_posts.json
  def create
    @user_post = UserPost.new(user_post_params)

    respond_to do |format|
      if @user_post.save
        format.html { redirect_to @user_post, notice: "User post was successfully created." }
        format.json { render :show, status: :created, location: @user_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_posts/1 or /user_posts/1.json
  def update
    respond_to do |format|
      if @user_post.update(user_post_params)
        format.html { redirect_to @user_post, notice: "User post was successfully updated." }
        format.json { render :show, status: :ok, location: @user_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_posts/1 or /user_posts/1.json
  def destroy
    @user_post.destroy!

    respond_to do |format|
      format.html { redirect_to user_posts_path, status: :see_other, notice: "User post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_post
      @user_post = UserPost.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_post_params
      params.expect(user_post: [ :content ])
    end
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/views/user_posts/_form.html.erb
<%= form_with(model: user_post, class: "contents") do |form| %>
  <% if user_post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(user_post.errors.count, "error") %> prohibited this user_post from being saved:</h2>

      <ul class="list-disc ml-6">
        <% user_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.text_field :content, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": user_post.errors[:content].none?, "border-red-400 focus:outline-red-600": user_post.errors[:content].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/user_posts/_user_post.html.erb
<article id="<%= dom_id user_post %>" class="my-5 space-y-5">
  <div>
    <h1 class = "my-5 text-3x1 font-semibold"> <%= user_post.user.email %></h1>
      <div>
        <%= user_post.content %>
      </div>
  </div>
</article>

app/views/user_posts/edit.html.erb
<% content_for :title, "Editing user post" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user post</h1>

  <%= render "form", user_post: @user_post %>

  <%= link_to "Show this user post", @user_post, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to user posts", user_posts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/user_posts/index.html.erb
<% content_for :title, "User posts" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">User posts</h1>
    <%= link_to "New user post", new_user_post_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="user_posts" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @user_posts.any? %>
      <% @user_posts.each do |user_post| %>
        <div class="flex justify-between items-center">
          <%= render user_post %>
          <div class="space-x-2">
            <% if user_signed_in? %>
            <%= link_to "Show", user_post, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_user_post_path(user_post), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="inline-block">
              <%= button_to "Destroy", user_post, method: :delete, class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
            <%end%>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No user posts found.</p>
    <% end %>
  </div>
</div>

app/views/user_posts/new.html.erb
<% content_for :title, "New user post" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user post</h1>

  <%= render "form", user_post: @user_post %>

  <%= link_to "Back to user posts", user_posts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/user_posts/show.html.erb
<% content_for :title, "Showing user post" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing user post</h1>

  <%= render @user_post %>

  <%= link_to "Edit this user post", edit_user_post_path(@user_post), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to user posts", user_posts_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this user post", @user_post, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>